In [1]:
import numpy as np

In [2]:
a13=np.array([1,2,3])
a12=np.array([11,12])
a23=np.array([[21,22,23],[24,25,26]])
a22=np.array([[31,32],[33,34]])
a33=np.array([[91,92,93],[94,95,96],[97,98,99]])
a32=np.array([[81,82],[84,85],[86,87]])

In [3]:
#array multiplication

In [4]:
np.dot(a13,a33)

array([570, 576, 582])

In [5]:
np.dot(a23,a32)


array([[5527, 5593],
       [6280, 6355]])

In [6]:
np.dot(a32,a23)

array([[3669, 3832, 3995],
       [3804, 3973, 4142],
       [3894, 4067, 4240]])

In [7]:
#array addition

In [8]:
print(np.sum([a13,a23]))
print(a13)
print(a23)

[[22 24 26]
 [25 27 29]]
[1 2 3]
[[21 22 23]
 [24 25 26]]


In [59]:
np.sum([a13,a23],axis=0)

array([[22, 24, 26],
       [25, 27, 29]])

In [10]:
b13=np.array([100,102,103])
b12=np.array([110,111])
b23=np.array([[210,220,230],[240,250,260]])
b22=np.array([[310,320],[330,340]])
b33=np.array([[910,920,930],[940,950,960],[970,980,990]])
b32=np.array([[810,820],[840,850],[860,870]])

In [11]:
np.sum([a13,b13],axis=0)

array([101, 104, 106])

In [12]:
np.sum([a33,b33],axis=0)

array([[1001, 1012, 1023],
       [1034, 1045, 1056],
       [1067, 1078, 1089]])

In [13]:
print(a33)
print(b33)

[[91 92 93]
 [94 95 96]
 [97 98 99]]
[[910 920 930]
 [940 950 960]
 [970 980 990]]


In [14]:
#subtraction

In [15]:
np.subtract(b33,a33)

array([[819, 828, 837],
       [846, 855, 864],
       [873, 882, 891]])

In [16]:
#zeros,full,con

In [17]:
a=np.zeros((3,2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [18]:
b= np.full((3,3),1)
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [19]:
c=np.concatenate([a23,b22],axis=1)#clearly check the row and col, if number of rows are equal we can go for axis=1
print(c)

[[ 21  22  23 310 320]
 [ 24  25  26 330 340]]


In [20]:
d= np.concatenate([b23,b33],axis=0)#if number of columns are equal then axis =0
print(d)

[[210 220 230]
 [240 250 260]
 [910 920 930]
 [940 950 960]
 [970 980 990]]


In [21]:
#stack , vstack ,hstack

In [22]:
s1,s2,s3= np.stack((a33,b33),axis=1)#same shape can be stacked and number arrays formed is equal to the number of rows
print (s1.shape,s1)

(2, 3) [[ 91  92  93]
 [910 920 930]]


In [23]:
s11,s12 =np.stack((a23,b23),axis=1)#axis=1 denotes 1st row of is b23 is stacked under 1st row a23.
print(s11)

[[ 21  22  23]
 [210 220 230]]


In [24]:
s01,s02=np.stack((a23,b23))
print(s01)

[[21 22 23]
 [24 25 26]]


In [25]:
np.vstack([a12,b12])

array([[ 11,  12],
       [110, 111]])

In [26]:
np.vstack([a33,b33])#returns a single array

array([[ 91,  92,  93],
       [ 94,  95,  96],
       [ 97,  98,  99],
       [910, 920, 930],
       [940, 950, 960],
       [970, 980, 990]])

In [27]:
np.hstack([a33,b33])

array([[ 91,  92,  93, 910, 920, 930],
       [ 94,  95,  96, 940, 950, 960],
       [ 97,  98,  99, 970, 980, 990]])

In [28]:
#random, 

In [29]:
np.random.random((2,3))

array([[0.96061637, 0.40768793, 0.74446127],
       [0.01892367, 0.03414772, 0.69948583]])

In [30]:
#linspace,full,equal,array_equal

In [31]:
np.linspace(3,6,10)

array([3.        , 3.33333333, 3.66666667, 4.        , 4.33333333,
       4.66666667, 5.        , 5.33333333, 5.66666667, 6.        ])

In [32]:
np.full([3,4],5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [33]:
np.equal(a33,b33)#checks same shape of arrays

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [34]:
np.array_equal(a12,a33)#any shape of array can be passed

False

In [35]:
print(a12)
print(a13)
print(a22)
print(a23)
print(a32)
print(a33)

[11 12]
[1 2 3]
[[31 32]
 [33 34]]
[[21 22 23]
 [24 25 26]]
[[81 82]
 [84 85]
 [86 87]]
[[91 92 93]
 [94 95 96]
 [97 98 99]]


In [36]:
#mulitply and dot difference

In [37]:
np.multiply(a33,a13)

array([[ 91, 184, 279],
       [ 94, 190, 288],
       [ 97, 196, 297]])

In [38]:
print(a33,a13)

[[91 92 93]
 [94 95 96]
 [97 98 99]] [1 2 3]


In [39]:
np.dot(a13,a33)

array([570, 576, 582])

In [40]:
np.dot(a33,a13)

array([554, 572, 590])

In [41]:
print(b33,b12)

[[910 920 930]
 [940 950 960]
 [970 980 990]] [110 111]


In [42]:
np.dot(a33,b13)#hence dot is best way for multiplication an array of m*n can be multiplied with p*q , if n=p,
                #or p=1&n=q it returns array of lowest shape

array([28063, 28978, 29893])

In [43]:
print(a23)
print(b13)

[[21 22 23]
 [24 25 26]]
[100 102 103]


In [44]:
np.dot(a22,a12)

array([725, 771])

In [45]:
#mean , median ,std

In [46]:
np.mean(a12)

11.5

In [47]:
np.mean(a33)#default axis=None

95.0

In [48]:
np.mean(a33,axis=0)#mean is calculated basis of each column

array([94., 95., 96.])

In [49]:
print(a33)

[[91 92 93]
 [94 95 96]
 [97 98 99]]


In [50]:
np.mean(a33,axis=1)#cal basis of each row

array([92., 95., 98.])

In [51]:
np.median(a33)

95.0

In [52]:
np.median(a33,axis=0)#mean is calculated basis of each column

array([94., 95., 96.])

In [53]:
std1 = np.array([21,90,100])
std2= np.array([[13,19,20],[40,32,78],[45,79,56]])


In [54]:
np.std(std1)

35.122009560324926

In [55]:
np.std(std2,axis=0)#std of (13,40,45) of each col

array([14.05544576, 25.77250904, 23.9072281 ])

In [56]:
np.std(std2,axis=1)#std dev of (13,19,20)

array([ 3.09120617, 20.06655592, 14.16568624])

In [57]:
np.std(std2)#axis=None

23.157005712748074

In [ ]:
#determinant

In [65]:
#determinant of a square matrix can only be found out, where m=n
#np.linalg.det()

In [66]:
det1=np.array([[2,33,45],[20,98,67],[9,67,44]])

In [67]:
np.linalg.det(det1)

11114.99999999999

In [68]:
#shape , reshape

In [69]:
a32.shape =(2,3)

In [70]:
a32

array([[81, 82, 84],
       [85, 86, 87]])

In [71]:
cRS = a23.reshape(3,2)

In [72]:
print(cRS)
print (a23)

[[21 22]
 [23 24]
 [25 26]]
[[21 22 23]
 [24 25 26]]


In [78]:
aRS = np.arange(24)

In [75]:
print(aRS)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [81]:
aRS1,aRS2=aRS.reshape(2,3,4) #2 indicates spliting the array into 2 different arrays,
#no. of elements in an array must be equal to the product of all arguemnets passed in reshape

In [82]:
print (aRS1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [83]:
#empty , ones, logspaces

In [89]:
np.empty([4,5],dtype=int)

array([[-1934826392,         565,          47,           0,           0],
       [          0,           0,           0,           0,         112],
       [ 1868767867,   975332708,   779120162,  1953525093,   878389369],
       [  693974316,  1696738338,  1969448312,  1852795252,  1970234207]])

In [90]:
np.ones([3,4],dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [91]:
np.ones([2,3])

array([[1., 1., 1.],
       [1., 1., 1.]])

In [92]:
#asarray

In [93]:
t1 = (23,24,56,78)
at1=np.asarray(t1)
print(at1)

[23 24 56 78]


In [98]:
t2 =[[289,356],[23,908]]
at2=np.asarray(t2,dtype=float)
print(at2)

[[289. 356.]
 [ 23. 908.]]


In [107]:
np.logspace(1,2,num=5,endpoint=True) #endpoint to specify it ends at log2

array([ 10.        ,  17.7827941 ,  31.6227766 ,  56.23413252,
       100.        ])

In [108]:
#np.nditer

In [111]:
it = np.arange(0,60,5)

In [114]:
it1= it.reshape(4,3)

In [120]:
for i in np.nditer(it1):
    if i == 5:
        print ('got it')
    print (i)

0
got it
5
10
15
20
25
30
35
40
45
50
55


In [121]:
#transpose of matrix , types of order (C,F), flat , flatten 


In [122]:
tran = np.arange(0,60,5)
tran = tran.reshape(3,4)

In [123]:
print (tran)

[[ 0  5 10 15]
 [20 25 30 35]
 [40 45 50 55]]


In [124]:
tranb = tran.T #method 1

In [125]:
tranb

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [126]:
np.transpose(tran) #method 2

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [127]:
t33 =a33.T

In [128]:
print(a33,t33)

[[91 92 93]
 [94 95 96]
 [97 98 99]] [[91 94 97]
 [92 95 98]
 [93 96 99]]


In [138]:
order1 = np.arange (0,60,5)

In [139]:
order1 = order1.reshape(4,3,order='F') #order set to F fortan 

In [141]:
order1

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [142]:
order2 = np.arange(0,60,5)# default is order c  
order2= order2.reshape(4,3)
print(order2)

[[ 0  5 10]
 [15 20 25]
 [30 35 40]
 [45 50 55]]


In [144]:
#flat it returns the (n+1)th element in the array if starting is considered to be 0
order2.flat[5]

25

In [145]:
order2.flatten() #converts into 1d array 

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [146]:
order2.flatten(order='F')

array([ 0, 15, 30, 45,  5, 20, 35, 50, 10, 25, 40, 55])

In [151]:
order2.ravel(order='F')

array([ 0, 15, 30, 45,  5, 20, 35, 50, 10, 25, 40, 55])

In [152]:
#roll axis


In [153]:
ra = np.arange(8).reshape(2,2,2)

In [155]:
print (ra)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [156]:
np.rollaxis(ra,2)

array([[[0, 2],
        [4, 6]],

       [[1, 3],
        [5, 7]]])

In [158]:
np.rollaxis(ra,2,1)

array([[[0, 2],
        [1, 3]],

       [[4, 6],
        [5, 7]]])

In [159]:
#bitwiseoperators

In [160]:
bit1,bit2 = 13,17

In [161]:
print (bin(bit1),bin(bit2))

0b1101 0b10001


In [164]:
np.bitwise_and(a33,b33)

array([[10, 24,  0],
       [12, 22, 64],
       [64, 64, 66]], dtype=int32)

In [166]:
np.bitwise_or(13,17)

29

In [167]:
np.binary_repr(13,width=8)

'00001101'

In [168]:
#char, capitalize, replace, encode , decode

In [169]:
np.char.center('hello',22,fillchar='&')

array('&&&&&&&&hello&&&&&&&&&', dtype='<U22')

In [170]:
np.char.capitalize('hello world')

array('Hello world', dtype='<U11')

In [171]:
np.char.title('how are you ?')

array('How Are You ?', dtype='<U13')

In [172]:
np.char.replace('how is he?','he','she')

array('how is she?', dtype='<U11')

In [175]:
e1=np.char.encode('abhishek','cp500')
print(e1)

b'\x81\x82\x88\x89\xa2\x88\x85\x92'


In [177]:
np.char.decode(e1,'cp500')

array('abhishek', dtype='<U8')

In [178]:
#trignometry

In [179]:
tri = np.array([0,30,45,60,90]) 

In [181]:

sin=np.sin(tri*np.pi/180)
print(sin)

[0.         0.5        0.70710678 0.8660254  1.        ]


In [183]:
inv =np.arcsin(sin)
print(inv)

[0.         0.52359878 0.78539816 1.04719755 1.57079633]


In [184]:
print(np.degrees(inv))

[ 0. 30. 45. 60. 90.]


In [185]:
#rounding, floor,ceil

In [186]:
rd1 = np.array([1.0,5.55, 123, 0.567, 25.532])

In [187]:
print(rd1.round())

[  1.   6. 123.   1.  26.]


In [188]:
print(rd1)

[  1.      5.55  123.      0.567  25.532]


In [190]:
print(np.around(rd1,decimals=1))

[  1.    5.6 123.    0.6  25.5]


In [191]:
print(np.around(rd1,decimals=-1))

[  0.  10. 120.   0.  30.]


In [192]:
#floor when it is applied it return the number not greater than input parameter, ceil is viceversa

In [193]:
np.floor(rd1)

array([  1.,   5., 123.,   0.,  25.])

In [195]:
np.ceil(rd1)

array([  1.,   6., 123.,   1.,  26.])

In [196]:
#reciprocal , power , complex numbers, amin , amax

In [197]:
np.reciprocal(rd1)

array([1.        , 0.18018018, 0.00813008, 1.76366843, 0.03916654])

In [198]:
np.power(a33,2)

array([[8281, 8464, 8649],
       [8836, 9025, 9216],
       [9409, 9604, 9801]], dtype=int32)

In [200]:
np.remainder(a33,a13)

array([[0, 0, 0],
       [0, 1, 0],
       [0, 0, 0]], dtype=int32)

In [201]:
print(a33,a13)

[[91 92 93]
 [94 95 96]
 [97 98 99]] [1 2 3]


In [ ]:
#2 dismilar array cannot be used in remainder , only (1,m) or (n,1) can be used as it is broadcasted

In [205]:
print(a33,b33)

[[91 92 93]
 [94 95 96]
 [97 98 99]] [[910 920 930]
 [940 950 960]
 [970 980 990]]


In [207]:
mi1 = np.array([[3,7,5],[8,4,3],[2,4,9]]) 

In [208]:
np.amin(mi1)

2

In [209]:
np.amin(mi1,axis=0)

array([2, 4, 3])

In [211]:
np.amin(mi1,axis=1)

array([3, 3, 2])

In [212]:
np.amin(a33)

91

In [213]:
np.amin(a33,axis=1)#check row wise lowest

array([91, 94, 97])

In [214]:
np.amin(a33,axis=0)

array([91, 92, 93])

In [220]:
mi2= np.array([[2,3,9],[8,10,11],[1,19,17]])

In [222]:
np.amin(mi2,axis=0)#check column wise lowest

array([1, 3, 9])

In [223]:
np.amax(a33)

99

In [224]:
print(np.amax(a33,axis=0),np.amax(a33,axis=1))

[97 98 99] [93 96 99]


In [225]:
#ptp , percentile ,average,var

In [226]:
np.ptp(mi1)

7

In [227]:
np.ptp(mi1,axis=0)

array([6, 3, 6])

In [228]:
np.ptp(mi1,axis=1)

array([4, 5, 7])

In [229]:
np.ptp(a33,axis=0) #checks the range between per column

array([6, 6, 6])

In [230]:
np.ptp(a33,axis=1) #check the range between per row

array([2, 2, 2])

In [231]:
np.average(np.array([1,2,3,4]))

2.5

In [232]:
wts=[3,2,1,1]

In [233]:
np.average(np.array([1,2,3,4]),weights=wts)

2.0

In [234]:
np.average(np.array([1,2,3,4]),weights=wts,returned=True)#returned = true denotes it gives average weighted sum

(2.0, 7.0)

In [235]:
np.var(a33)

6.666666666666667

In [236]:
np.var(a33,axis=1)#per row variance

array([0.66666667, 0.66666667, 0.66666667])

In [237]:
np.var(a33,axis=0)#per column variance

array([6., 6., 6.])