In [2]:
import numpy as np

In [3]:
a13=np.array([1,2,3])
a12=np.array([11,12])
a23=np.array([[21,22,23],[24,25,26]])
a22=np.array([[31,32],[33,34]])
a33=np.array([[91,92,93],[94,95,96],[97,98,99]])
a32=np.array([[81,82],[84,85],[86,87]])

In [4]:
#array multiplication

In [5]:
np.dot(a13,a33)

array([570, 576, 582])

In [6]:
np.dot(a23,a32)


array([[5527, 5593],
       [6280, 6355]])

In [7]:
np.dot(a32,a23)

array([[3669, 3832, 3995],
       [3804, 3973, 4142],
       [3894, 4067, 4240]])

In [8]:
#array addition

In [9]:
print(np.sum([a13,a23]))
print(a13)
print(a23)

[[22 24 26]
 [25 27 29]]
[1 2 3]
[[21 22 23]
 [24 25 26]]


In [10]:
np.sum([a13,a23],axis=0)

array([[22, 24, 26],
       [25, 27, 29]])

In [11]:
b13=np.array([100,102,103])
b12=np.array([110,111])
b23=np.array([[210,220,230],[240,250,260]])
b22=np.array([[310,320],[330,340]])
b33=np.array([[910,920,930],[940,950,960],[970,980,990]])
b32=np.array([[810,820],[840,850],[860,870]])

In [12]:
np.sum([a13,b13],axis=0)

array([101, 104, 106])

In [13]:
np.sum([a33,b33],axis=0)

array([[1001, 1012, 1023],
       [1034, 1045, 1056],
       [1067, 1078, 1089]])

In [14]:
print(a33)
print(b33)

[[91 92 93]
 [94 95 96]
 [97 98 99]]
[[910 920 930]
 [940 950 960]
 [970 980 990]]


In [15]:
#subtraction

In [16]:
np.subtract(b33,a33)

array([[819, 828, 837],
       [846, 855, 864],
       [873, 882, 891]])

In [17]:
#zeros,full,con

In [18]:
a=np.zeros((3,2))
print(a)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [19]:
b= np.full((3,3),1)
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [20]:
c=np.concatenate([a23,b22],axis=1)#clearly check the row and col, if number of rows are equal we can go for axis=1
print(c)

[[ 21  22  23 310 320]
 [ 24  25  26 330 340]]


In [21]:
d= np.concatenate([b23,b33],axis=0)#if number of columns are equal then axis =0
print(d)

[[210 220 230]
 [240 250 260]
 [910 920 930]
 [940 950 960]
 [970 980 990]]


In [22]:
#stack , vstack ,hstack

In [24]:
s1,s2,s3= np.stack((a33,b33),axis=1)#same shape can be stacked and number arrays formed is equal to the number of rows
print (s1.shape,s1)

(2, 3) [[ 91  92  93]
 [910 920 930]]


In [32]:
s11,s12 =np.stack((a23,b23),axis=1)#axis=1 denotes 1st row of is b23 is stacked under 1st row a23.
print(s11)

[[ 21  22  23]
 [210 220 230]]


In [34]:
s01,s02=np.stack((a23,b23))
print(s01)

[[21 22 23]
 [24 25 26]]


In [38]:
np.vstack([a12,b12])

array([[ 11,  12],
       [110, 111]])

In [39]:
np.vstack([a33,b33])#returns a single array

array([[ 91,  92,  93],
       [ 94,  95,  96],
       [ 97,  98,  99],
       [910, 920, 930],
       [940, 950, 960],
       [970, 980, 990]])

In [44]:
np.hstack([a33,b33])

array([[ 91,  92,  93, 910, 920, 930],
       [ 94,  95,  96, 940, 950, 960],
       [ 97,  98,  99, 970, 980, 990]])

In [45]:
#random, 

In [48]:
np.random.random((2,3))

array([[0.53163168, 0.14949894, 0.76528329],
       [0.43007515, 0.98367142, 0.20370483]])

In [49]:
#linspace,full,equal,array_equal

In [51]:
np.linspace(3,6,10)

array([3.        , 3.33333333, 3.66666667, 4.        , 4.33333333,
       4.66666667, 5.        , 5.33333333, 5.66666667, 6.        ])

In [52]:
np.full([3,4],5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [55]:
np.equal(a33,b33)#checks same shape of arrays

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [57]:
np.array_equal(a12,a33)#any shape of array can be passed

False

In [59]:
print(a12)
print(a13)
print(a22)
print(a23)
print(a32)
print(a33)

[11 12]
[1 2 3]
[[31 32]
 [33 34]]
[[21 22 23]
 [24 25 26]]
[[81 82]
 [84 85]
 [86 87]]
[[91 92 93]
 [94 95 96]
 [97 98 99]]


In [60]:
#mulitply and dot difference

In [67]:
np.multiply(a33,a13)

array([[ 91, 184, 279],
       [ 94, 190, 288],
       [ 97, 196, 297]])

In [65]:
print(a33,a13)

[[91 92 93]
 [94 95 96]
 [97 98 99]] [1 2 3]


In [70]:
np.dot(a13,a33)

array([570, 576, 582])

In [80]:
np.dot(a33,a13)

array([554, 572, 590])

In [75]:
print(b33,b12)

[[910 920 930]
 [940 950 960]
 [970 980 990]] [110 111]


In [92]:
np.dot(a33,b13)#hence dot is best way gfor multiplication an array of m*n can be multiplied with p*q , if n=p,
                #or p=1&n=q it returns array of lowest shape

array([28063, 28978, 29893])

In [93]:
print(a23)
print(b13)

[[21 22 23]
 [24 25 26]]
[100 102 103]


In [94]:
np.dot(a22,a12)

array([725, 771])